language: cpp
cache: apt
compiler:
  - gcc
before_install: sudo apt-get update
install: 
  - sudo apt-get install git build-essential libssl-dev libboost-all-dev libdb++-dev libminiupnpc-dev qt-sdk -y
  - git clone https://github.com/devrandom/gitian-builder.git
  -sudo apt-get install git apache2 apt-cacher-ng python-vm-builder ruby qemu-utils
  - sudo apt-get install qemu-kvm         # for KVM mode
script:
  - # cd src && make -f makefile.unix && cd .. && qmake && make
  - cd gitian-builder/
  - bin/make-base-vm
  - bin/make-base-vm --arch i386
  - mkdir -p inputs; cd inputs/
  - wget 'http://miniupnp.free.fr/files/download.php?file=miniupnpc-1.6.tar.gz' -O miniupnpc-1.6.tar.gz
  - wget 'http://www.openssl.org/source/openssl-1.0.1c.tar.gz'
  - wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
  - wget 'http://zlib.net/zlib-1.2.6.tar.gz'
  - wget 'ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng-1.5.9.tar.gz'
  - wget 'http://fukuchi.org/works/qrencode/qrencode-3.2.0.tar.bz2'
  - wget 'http://downloads.sourceforge.net/project/boost/boost/1.50.0/boost_1_50_0.tar.bz2'
  - wget 'http://releases.qt-project.org/qt4/source/qt-everywhere-opensource-src-4.8.3.tar.gz'
  - cd ..
  - ./bin/gbuild ../contrib/gitian-descriptors/boost-win32.yml
  - mv build/out/boost-win32-1.50.0-gitian2.zip inputs/
  - ./bin/gbuild ../contrib/gitian-descriptors/qt-win32.yml
  - mv build/out/qt-win32-4.8.3-gitian-r1.zip inputs/
  - ./bin/gbuild ../contrib/gitian-descriptors/deps-win32.yml
  - mv build/out/bitcoin-deps-0.0.5.zip inputs/
  - ./bin/gbuild --commit bitcoin=v${VERSION} ../contrib/gitian-descriptors/gitian.yml
  - ./bin/gbuild --commit bitcoin=v${VERSION} ../contrib/gitian-descriptors/gitian-win32.yml
